version: '3'

services:
  db:
    container_name: postgresql
    image: postgres
    volumes:
      - ./postgres:/data/db
    ports:
      - 7894:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dbdv
    restart: always

  redis:
    container_name: redis
    image: redis:6.2-alpine
    volumes:
      - ./redis:/data/db
    ports:
      - 6379:6379
    restart: always

  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    restart: always

  app:
    build: .
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    depends_on:
      - db
      - redis
      - minio
